services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  
  front-end:
    image: ghcr.io/mcmastercce/bvd-103-mcmasterful-books/mcmasterful-books-docker:main 
    volumes:
      - ./adapter:/source/adapter
  
  mongo-2:
    image: mongo:latest
  
  server:
    image: node:20
    volumes:
      - ./:/app
    working_dir: /app
    command: npx -y tsx ./index.ts
  
  server-2:
    image: node:20
    volumes:
      - ./:/app
    working_dir: /app
    command: npx -y tsx ./index.ts
  
  server-3:
    image: node:20
    volumes:
      - ./:/app
    working_dir: /app
    command: npx -y tsx ./index.ts

  rabbitmq-2:
    image: rabbitmq:3-management
    container_name: rabbitmq2
    ports:
        - 5672:5672
        - 15672:15672