/* tslint:disable */
/* eslint-disable */
/**
 * assignment-template
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateOrUpdateBook200Response
 */
export interface CreateOrUpdateBook200Response {
    /**
     * A unique identifier for a particular book
     * @type {string}
     * @memberof CreateOrUpdateBook200Response
     */
    id: string;
}

/**
 * Check if a given object implements the CreateOrUpdateBook200Response interface.
 */
export function instanceOfCreateOrUpdateBook200Response(value: object): boolean {
    if (!('id' in value)) return false;
    return true;
}

export function CreateOrUpdateBook200ResponseFromJSON(json: any): CreateOrUpdateBook200Response {
    return CreateOrUpdateBook200ResponseFromJSONTyped(json, false);
}

export function CreateOrUpdateBook200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrUpdateBook200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
    };
}

export function CreateOrUpdateBook200ResponseToJSON(value?: CreateOrUpdateBook200Response | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

