/* tslint:disable */
/* eslint-disable */
/**
 * assignment-template
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FulfilledBooksInner
 */
export interface FulfilledBooksInner {
    /**
     * 
     * @type {number}
     * @memberof FulfilledBooksInner
     */
    numberOfBooks: number;
    /**
     * The name of a shelf
     * @type {string}
     * @memberof FulfilledBooksInner
     */
    shelf: string;
    /**
     * A unique identifier for a particular book
     * @type {string}
     * @memberof FulfilledBooksInner
     */
    book: string;
}

/**
 * Check if a given object implements the FulfilledBooksInner interface.
 */
export function instanceOfFulfilledBooksInner(value: object): boolean {
    if (!('numberOfBooks' in value)) return false;
    if (!('shelf' in value)) return false;
    if (!('book' in value)) return false;
    return true;
}

export function FulfilledBooksInnerFromJSON(json: any): FulfilledBooksInner {
    return FulfilledBooksInnerFromJSONTyped(json, false);
}

export function FulfilledBooksInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): FulfilledBooksInner {
    if (json == null) {
        return json;
    }
    return {
        
        'numberOfBooks': json['numberOfBooks'],
        'shelf': json['shelf'],
        'book': json['book'],
    };
}

export function FulfilledBooksInnerToJSON(value?: FulfilledBooksInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'numberOfBooks': value['numberOfBooks'],
        'shelf': value['shelf'],
        'book': value['book'],
    };
}

