/* tslint:disable */
/* eslint-disable */
/**
 * assignment-template
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FulfilledBooksInner } from './FulfilledBooksInner';
import {
    FulfilledBooksInnerFromJSON,
    FulfilledBooksInnerFromJSONTyped,
    FulfilledBooksInnerToJSON,
} from './FulfilledBooksInner';

/**
 * 
 * @export
 * @interface FulfilOrderRequest
 */
export interface FulfilOrderRequest {
    /**
     * An array listing how many copies of each book are taken from a given shelf while fulfilling an order
     * @type {Array<FulfilledBooksInner>}
     * @memberof FulfilOrderRequest
     */
    booksFulfilled: Array<FulfilledBooksInner>;
}

/**
 * Check if a given object implements the FulfilOrderRequest interface.
 */
export function instanceOfFulfilOrderRequest(value: object): boolean {
    if (!('booksFulfilled' in value)) return false;
    return true;
}

export function FulfilOrderRequestFromJSON(json: any): FulfilOrderRequest {
    return FulfilOrderRequestFromJSONTyped(json, false);
}

export function FulfilOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): FulfilOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'booksFulfilled': ((json['booksFulfilled'] as Array<any>).map(FulfilledBooksInnerFromJSON)),
    };
}

export function FulfilOrderRequestToJSON(value?: FulfilOrderRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'booksFulfilled': ((value['booksFulfilled'] as Array<any>).map(FulfilledBooksInnerToJSON)),
    };
}

