/* tslint:disable */
/* eslint-disable */
/**
 * assignment-template
 * This is a template repository for the first assignment in BVD 103 at McMaster Continuing Education.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PlaceOrderRequest
 */
export interface PlaceOrderRequest {
    /**
     * An array listing all the books ordered by Id. Multiple copies of a book are listed as duplicate IDs
     * @type {Array<string>}
     * @memberof PlaceOrderRequest
     */
    order: Array<string>;
}

/**
 * Check if a given object implements the PlaceOrderRequest interface.
 */
export function instanceOfPlaceOrderRequest(value: object): boolean {
    if (!('order' in value)) return false;
    return true;
}

export function PlaceOrderRequestFromJSON(json: any): PlaceOrderRequest {
    return PlaceOrderRequestFromJSONTyped(json, false);
}

export function PlaceOrderRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PlaceOrderRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'order': json['order'],
    };
}

export function PlaceOrderRequestToJSON(value?: PlaceOrderRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'order': value['order'],
    };
}

