on: push
jobs:
  versions:
    runs-on: windows-latest
    steps:
      - run: node --version
      - run: npm --version
  linting-job:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run NPM install
        run: npm install
      - run: npx eslint .
  indexNoEmit-job:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run NPM install
        run: npm install
      - run: tsc ./src/index.ts --noEmit
  vitest-job:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Run NPM install
        run: npm install
      - run: npx vitest
