on: push
jobs:
  versions:
    runs-on: windows-latest
    steps:
      - run: node --version
      - run: npm --version
  first-job:
    runs-on: windows-latest
    steps:
      - run: npx eslint --fix .
  second-job:
    runs-on: windows-latest
    steps:
      - run: tsc ./src/index.ts --noEmit
