on: push
jobs:
  versions:
    runs-on: windows-latest
    steps:
      - run: node --version
      - run: npm --version
  eslint-job:
    runs-on: windows-latest
    steps:
      - run: npx eslint --fix .
  noEmit-job:
    runs-on: windows-latest
    steps:
      - run: tsc ./src/index.ts --noEmit
  vitest-job:
    runs-on: windows-latest
    steps:
      - run: npx vitest
